import type { CogCapabilities } from '../adapters/mmgisAPI'
import type { Layer, CategoricalStop, CogData } from './types'

type MMGISLegendEntry = {
    shape?: string
    color?: string
    value?: string | number
    label?: string
    hideFromLegend?: boolean
}

type MMGISLayerConfig = {
    display_name?: string
    description?: string
    _legend?: MMGISLegendEntry[]
    // Set by LayersTool.populateCogScale alongside `_legend` when it derives
    // that legend from the live COG colormap/rescale, rather than a mission
    // author's `variables.legend`/CSV. Lets this module tell the two apart —
    // both live in the same `_legend` field.
    _legendAutoGenerated?: boolean
    currentCogColormap?: string
    cogColormap?: string
    currentCogMin?: number
    cogMin?: number
    currentCogMax?: number
    cogMax?: number
    cogUnits?: string | null
}

const SCALE_SHAPES = ['continuous', 'discreet']

type NumericValue = { number: number; unit: string }

const NUMERIC_PREFIX = /^[+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/

/**
 * Reads a legend value as a number plus an optional trailing unit
 * (`'0.5 ppm'` -> 0.5 + 'ppm'). Null for anything that is not a plain number:
 * a word (`'example'`), or a binned label (`'0.5-1.0 m'`) whose remainder
 * reads as another number rather than as a unit.
 */
const parseNumericValue = (
    value: string | number | undefined,
): NumericValue | null => {
    const str = String(value ?? '').trim()
    const match = str.match(NUMERIC_PREFIX)
    if (!match) return null
    const unit = str.slice(match[0].length).trim()
    if (/^[+\-.\d]/.test(unit)) return null
    return { number: parseFloat(match[0]), unit }
}

/**
 * The numbers and shared unit behind a run of scale entries, or null when the
 * run is not one honest numeric scale: some value is not a number, or the
 * entries disagree on their unit (which is what a set of binned labels looks
 * like once each bin's remainder is read as a unit).
 */
const readScaleValues = (
    entries: MMGISLegendEntry[],
): { numbers: number[]; unit: string | null } | null => {
    const parsed = entries.map((entry) => parseNumericValue(entry.value))
    if (parsed.some((value) => value === null)) return null
    const values = parsed as NumericValue[]
    const units = new Set(values.map((value) => value.unit))
    if (units.size > 1) return null
    const [unit] = [...units]
    return { numbers: values.map((value) => value.number), unit: unit || null }
}

/**
 * A gradient bar can only stand in for a legend that is one uninterrupted
 * numeric scale. A legend that mixes scale runs with individually shaped
 * entries — the form LegendTool renders as a mix of bars and swatches — or one
 * whose scale values are words or bins, draws as labelled swatches instead of
 * a ramp whose bounds would be read off non-numeric text.
 */
const readGradient = (entries: MMGISLegendEntry[]) => {
    if (!entries.every((entry) => SCALE_SHAPES.includes(entry.shape ?? '')))
        return null
    const values = readScaleValues(entries)
    if (!values) return null
    return {
        stops: entries.map((entry) => entry.color || ''),
        min: Math.min(...values.numbers),
        max: Math.max(...values.numbers),
        unit: values.unit ? { label: values.unit } : null,
    }
}

const hasSwatch = (entry: MMGISLegendEntry): boolean =>
    Boolean(entry.color) &&
    (entry.value !== undefined || entry.label !== undefined)

const buildCategoricalFields = (
    entries: MMGISLegendEntry[],
): CategoricalStop[] =>
    entries.map((entry) => ({
        color: entry.color || '',
        label: String(entry.value ?? entry.label ?? ''),
    }))

/**
 * Shapes one layer's config into the legend model the UI renders.
 *
 * `cogCapabilities` comes from core over the request bus and carries two
 * separate answers: `hasColormap` builds the COG block, so the legend draws
 * the ramp and its bounds, while `canChangeColormap` decides whether that
 * block is editable. A layer can have the first without the second.
 *
 * `titilerUrl` likewise comes from core, already resolved; null leaves the
 * ramp swatches with nowhere to load from.
 */
export const buildLayerLegendData = (
    layerName: string,
    layerConfig: MMGISLayerConfig,
    opacities: Record<string, number> | null | undefined,
    visible: boolean,
    cogCapabilities: CogCapabilities | null | undefined,
    titilerUrl: string | null = null,
): Layer => {
    const opacity = opacities?.[layerName] ?? 1

    const cog: CogData | null = cogCapabilities?.hasColormap
        ? {
              isCog: true,
              editable: cogCapabilities.canChangeColormap === true,
              colormap: layerConfig.currentCogColormap || layerConfig.cogColormap || 'viridis',
              // A bound nobody configured stays null: printing an
              // invented 0/255 on an export reads as an authoritative
              // range the raster was never rescaled to.
              min: layerConfig.currentCogMin ?? layerConfig.cogMin ?? null,
              max: layerConfig.currentCogMax ?? layerConfig.cogMax ?? null,
              defaultMin: layerConfig.cogMin ?? 0,
              defaultMax: layerConfig.cogMax ?? 255,
              defaultColormap: layerConfig.cogColormap || 'viridis',
              units: layerConfig.cogUnits ?? null,
              titilerUrl,
          }
        : null

    const base: Layer = {
        id: layerName,
        title: layerConfig.display_name || layerName,
        description: layerConfig.description || null,
        opacity,
        visible,
        type: 'none',
        cog,
    }

    // A machine-derived `_legend` (populateCogScale's live colormap snapshot)
    // is not an authored legend, so it is ignored in favour of live cog data:
    // a consumer that prefers the cog block over an authored legend (the
    // export) falls through to that instead of this stale snapshot. Only when
    // there is a cog to prefer, though — populateCogScale also writes the
    // marker for layers core reports no colormap for (velocity fields), where
    // discarding it would throw away the only legend the layer has.
    const legend =
        layerConfig._legendAutoGenerated === true && cog
            ? undefined
            : layerConfig._legend
    const entries = Array.isArray(legend)
        ? legend.filter((entry) => entry.hideFromLegend !== true)
        : []
    if (entries.length === 0) {
        if (cog) {
            return {
                ...base,
                type: 'gradient',
                min: cog.min,
                max: cog.max,
                stops: null,
                unit: cog.units ? { label: cog.units } : null,
            }
        }
        return base
    }

    const gradient = readGradient(entries)
    if (gradient) return { ...base, type: 'gradient', ...gradient }
    if (entries.some(hasSwatch)) {
        return {
            ...base,
            type: 'categorical',
            categoricalStops: buildCategoricalFields(entries),
        }
    }
    return { ...base, type: 'text' }
}
