import type { CogCapabilities } from '../adapters/mmgisAPI'
import type { Layer, LegendType, CategoricalStop, CogData } from './types'

type MMGISLegendEntry = {
    shape?: string
    color?: string
    value?: string | number
    label?: string
    hideFromLegend?: boolean
}

type MMGISLayerConfig = {
    display_name?: string
    description?: string
    _legend?: MMGISLegendEntry[]
    // Set by LayersTool.populateCogScale alongside `_legend` when it derives
    // that legend from the live COG colormap/rescale, rather than a mission
    // author's `variables.legend`/CSV. Lets this module tell the two apart —
    // both live in the same `_legend` field.
    _legendAutoGenerated?: boolean
    currentCogColormap?: string
    cogColormap?: string
    currentCogMin?: number
    cogMin?: number
    currentCogMax?: number
    cogMax?: number
    cogUnits?: string | null
}

const detectLegendType = (legend: MMGISLegendEntry[] | undefined): LegendType => {
    if (!Array.isArray(legend) || legend.length === 0) return 'text'
    const first = legend[0]
    if (first.shape === 'continuous' || first.shape === 'discreet') return 'gradient'
    if (first.color && first.value !== undefined) return 'categorical'
    return 'text'
}

const buildGradientFields = (legend: MMGISLegendEntry[]) => {
    const stops = legend.map((entry) => entry.color || '')
    const values = legend.map((entry) => {
        const parsed = parseFloat(String(entry.value))
        return isNaN(parsed) ? entry.value : parsed
    })
    const numericValues = values.filter((v): v is number => typeof v === 'number')
    const min = numericValues.length > 0
        ? Math.min(...numericValues)
        : (values[values.length - 1] as number)
    const max = numericValues.length > 0
        ? Math.max(...numericValues)
        : (values[0] as number)
    let unit: { label: string } | null = null
    const firstVal = legend[0]?.value
    if (firstVal !== undefined) {
        const str = String(firstVal)
        // Anchored so the numeric prefix is matched greedily from the start
        // (no backtracking into it) — the unit is whatever's left after
        // that prefix, so a purely numeric value like '-0.1' or '10' yields
        // no unit instead of a digit-eating regex inventing one from it.
        const numericPrefix = str.match(
            /^[+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/
        )
        if (numericPrefix) {
            const remainder = str.slice(numericPrefix[0].length).trim()
            if (remainder.length > 0) unit = { label: remainder }
        }
    }
    return { stops, min, max, unit }
}

const buildCategoricalFields = (legend: MMGISLegendEntry[]): CategoricalStop[] =>
    legend
        .filter((entry) => !entry.hideFromLegend)
        .map((entry) => ({
            color: entry.color || '',
            label: String(entry.value || entry.label || ''),
        }))

/**
 * Shapes one layer's config into the legend model the UI renders.
 *
 * `cogCapabilities` comes from core over the request bus and carries two
 * separate answers: `hasColormap` builds the COG block, so the legend draws
 * the ramp and its bounds, while `canChangeColormap` decides whether that
 * block is editable. A layer can have the first without the second.
 *
 * `titilerUrl` likewise comes from core, already resolved; null leaves the
 * ramp swatches with nowhere to load from.
 */
export const buildLayerLegendData = (
    layerName: string,
    layerConfig: MMGISLayerConfig,
    opacities: Record<string, number> | null | undefined,
    visible: boolean,
    cogCapabilities: CogCapabilities | null | undefined,
    titilerUrl: string | null = null,
): Layer => {
    const opacity = opacities?.[layerName] ?? 1

    const cog: CogData | null = cogCapabilities?.hasColormap
        ? {
              isCog: true,
              editable: cogCapabilities.canChangeColormap === true,
              colormap: layerConfig.currentCogColormap || layerConfig.cogColormap || 'viridis',
              min: layerConfig.currentCogMin ?? layerConfig.cogMin ?? 0,
              max: layerConfig.currentCogMax ?? layerConfig.cogMax ?? 255,
              defaultMin: layerConfig.cogMin ?? 0,
              defaultMax: layerConfig.cogMax ?? 255,
              defaultColormap: layerConfig.cogColormap || 'viridis',
              units: layerConfig.cogUnits ?? null,
              titilerUrl,
          }
        : null

    const base: Layer = {
        id: layerName,
        title: layerConfig.display_name || layerName,
        description: layerConfig.description || null,
        opacity,
        visible,
        type: 'none',
        cog,
    }

    // A machine-derived `_legend` (populateCogScale's live colormap snapshot)
    // is not an authored legend — treat it the same as having none, so a
    // consumer that prefers the cog block over an authored legend (the
    // export) falls through to the live cog data instead of this stale
    // snapshot.
    const legend =
        layerConfig._legendAutoGenerated === true ? undefined : layerConfig._legend
    if (!legend || (Array.isArray(legend) && legend.length === 0)) {
        if (cog) {
            return {
                ...base,
                type: 'gradient',
                min: cog.min,
                max: cog.max,
                stops: null,
                unit: cog.units ? { label: cog.units } : null,
            }
        }
        return base
    }

    const legendType = detectLegendType(legend)
    if (legendType === 'gradient') {
        const { stops, min, max, unit } = buildGradientFields(legend)
        return { ...base, type: 'gradient', stops, min, max, unit }
    }
    if (legendType === 'categorical') {
        return {
            ...base,
            type: 'categorical',
            categoricalStops: buildCategoricalFields(legend),
        }
    }
    return { ...base, type: 'text' }
}
