import { test, expect } from 'vitest'
import { buildLayerLegendData } from '../buildLayerLegendData.ts'

// The verdicts core can return for a layer's colormap.
const NO_COG = { hasColormap: false, canChangeColormap: false }
const EDITABLE_COG = { hasColormap: true, canChangeColormap: true }

const legendFor = (cfg, capabilities = NO_COG, titilerUrl) =>
    buildLayerLegendData('layer', cfg, null, true, capabilities, titilerUrl)

const continuous = (...values) =>
    values.map((value, i) => ({
        shape: 'continuous',
        color: i === 0 ? '#000000' : '#ffffff',
        value,
    }))

test.describe('buildLayerLegendData', () => {
    test('builds a gradient from a continuous legend, with its unit', () => {
        const result = legendFor({ _legend: continuous('0 m', '100 m') })
        expect(result.type).toBe('gradient')
        expect(result.stops).toEqual(['#000000', '#ffffff'])
        expect(result.min).toBe(0)
        expect(result.max).toBe(100)
        expect(result.unit).toEqual({ label: 'm' })
    })

    // A purely numeric value must never invent a unit out of its own digits:
    // an unanchored numeric match backtracks into '-0.1' and reads '1' as the
    // unit.
    test('derives no unit from numeric values alone', () => {
        expect(legendFor({ _legend: continuous('-0.1', '1') }).unit).toBeNull()
    })

    test('builds categorical swatches, dropping hidden entries', () => {
        const legend = [
            { color: '#ff0000', value: 'water' },
            { color: '#00ff00', value: 'land', hideFromLegend: true },
            // A class keyed 0 is a real label, so the fallback to `label` has
            // to test for undefined rather than for truthiness.
            { color: '#0000ff', value: 0 },
        ]
        const result = legendFor({ _legend: legend })
        expect(result.type).toBe('categorical')
        expect(result.categoricalStops).toEqual([
            { color: '#ff0000', label: 'water' },
            { color: '#0000ff', label: '0' },
        ])
    })

    // An author-hidden nodata colour is not a ramp stop, and its value is not
    // a bound: -9999 would otherwise become the printed minimum.
    test('drops hidden entries from a gradient ramp too', () => {
        const legend = [
            ...continuous('0 m', '100 m'),
            {
                shape: 'continuous',
                color: '#ff00ff',
                value: '-9999 m',
                hideFromLegend: true,
            },
        ]
        const result = legendFor({ _legend: legend })
        expect(result.stops).toEqual(['#000000', '#ffffff'])
        expect(result.min).toBe(0)
        expect(result.max).toBe(100)
    })

    test('an all-hidden legend is treated as no legend', () => {
        const legend = [{ color: '#ff0000', value: 'water', hideFromLegend: true }]
        expect(legendFor({ _legend: legend }).type).toBe('none')
    })

    // The mixed form documented in docs/pages/Tools/Legend/Legend.md: runs of
    // discreet/continuous entries interleaved with individually shaped
    // circle/square/rect ones, all labelled with words. Deciding the type from
    // the first entry's shape alone would make the whole thing one gradient,
    // labelled with two of those words as its bounds.
    test('renders a mixed shape legend as swatches, not one gradient', () => {
        const legend = [
            { color: 'purple', shape: 'discreet', value: 'This' },
            { color: 'cyan', shape: 'discreet', value: 'is' },
            { color: 'purple', shape: 'continuous', value: 'what' },
            { color: 'pink', shape: 'circle', value: 'csv' },
            { color: 'crimson', shape: 'square', value: 'possibly' },
            { color: 'indigo', shape: 'rect', value: 'contain' },
        ]
        const result = legendFor({ _legend: legend })
        expect(result.type).toBe('categorical')
        expect(result.categoricalStops.map((s) => s.label)).toEqual([
            'This',
            'is',
            'what',
            'csv',
            'possibly',
            'contain',
        ])
        expect(result.stops).toBeUndefined()
    })

    // Binned labels parse to a number followed by the rest of the bin, which
    // is not a unit — '0.5-1.0 m' must not yield the unit '-1.0 m'.
    test('renders binned scale labels as swatches rather than inventing a unit', () => {
        const legend = [
            { color: '#111111', shape: 'discreet', value: '0.0-0.5 m' },
            { color: '#222222', shape: 'discreet', value: '0.5-1.0 m' },
        ]
        const result = legendFor({ _legend: legend })
        expect(result.type).toBe('categorical')
        expect(result.unit).toBeUndefined()
    })

    // populateCogScale (LayersTool) writes its derived colormap snapshot into
    // the same `_legend` field an authored legend uses, marking it with
    // `_legendAutoGenerated`. That marker must make it lose to the live cog
    // block rather than being treated as authored.
    test('an auto-generated _legend defers to the live cog bar', () => {
        const cfg = {
            _legend: continuous('0 m', '10 m'),
            _legendAutoGenerated: true,
            cogColormap: 'viridis',
            cogMin: 2,
            cogMax: 8,
            cogUnits: 'K',
        }
        const result = legendFor(cfg, EDITABLE_COG)
        expect(result.stops).toBeNull()
        expect(result.min).toBe(2)
        expect(result.max).toBe(8)
        expect(result.unit).toEqual({ label: 'K' })
        expect(result.cog?.colormap).toBe('viridis')
    })

    // populateCogScale also runs for velocity layers, which core reports no
    // colormap for. With no live cog data to prefer, the derived `_legend` is
    // the only legend the layer has, so it renders rather than being dropped.
    test('renders an auto-generated _legend when there is no cog', () => {
        const cfg = {
            _legend: continuous('0 m/s', '10 m/s'),
            _legendAutoGenerated: true,
        }
        const result = legendFor(cfg)
        expect(result.cog).toBeNull()
        expect(result.type).toBe('gradient')
        expect(result.stops).toEqual(['#000000', '#ffffff'])
        expect(result.unit).toEqual({ label: 'm/s' })
    })

    // The common shape for a mission raster: a configured legend AND a COG
    // colormap. The legend decides how the bar is drawn; the COG block has to
    // survive that branch or the layer silently loses its colormap controls.
    test('keeps COG metadata for a capable layer that also has a legend', () => {
        const cfg = { _legend: continuous('0 m', '10 m'), cogColormap: 'viridis' }
        const result = legendFor(cfg, EDITABLE_COG)
        expect(result.stops).toEqual(['#000000', '#ffffff'])
        expect(result.cog?.editable).toBe(true)
    })

    test('prefers the current colormap and rescale over the configured ones', () => {
        const cfg = {
            cogColormap: 'viridis',
            cogMin: 0,
            cogMax: 1,
            currentCogColormap: 'rdbu_r',
            currentCogMin: -0.1,
            currentCogMax: 0.2,
        }
        const result = legendFor(cfg, EDITABLE_COG)
        expect(result.cog?.colormap).toBe('rdbu_r')
        expect(result.cog?.min).toBe(-0.1)
        expect(result.cog?.max).toBe(0.2)
        // The defaults stay pinned to the mission config so the control can
        // offer a reset.
        expect(result.cog?.defaultColormap).toBe('viridis')
        expect(result.cog?.defaultMin).toBe(0)
        expect(result.cog?.defaultMax).toBe(1)
    })

    // An unrescaled raster has no bounds to report; 0 and 255 would print on
    // the export as an authoritative range the layer was never rescaled to.
    test('leaves COG bounds null when the mission configures none', () => {
        const result = legendFor({ cogColormap: 'viridis' }, EDITABLE_COG)
        expect(result.cog?.min).toBeNull()
        expect(result.cog?.max).toBeNull()
        expect(result.min).toBeNull()
        expect(result.max).toBeNull()
    })

    // Core's answer already accounts for the mission-wide override, so a raw
    // config read would disagree with the service the tiles are drawn from.
    test('takes the service URL from core, not from the raw layer config', () => {
        const cfg = { cogColormap: 'plasma', titilerUrl: 'https://from-config.test' }
        const result = legendFor(cfg, EDITABLE_COG, 'https://from-core.test')
        expect(result.cog?.titilerUrl).toBe('https://from-core.test')
    })

})
