# Secret SHELLS only. Terraform defines the secrets' existence and names; the
# VALUES never pass through Terraform state. There is deliberately NO
# aws_secretsmanager_secret_version and NO random_password resource anywhere in
# this module — either would land a secret value in state.
#
# The four MMGIS-generated values below are filled by the CI secret bootstrap
# (#248) on the first deploy that finds their shell empty, and are never
# overwritten afterwards; the Mapbox token is hand-set. See the README.
#
# A `description` edit is an in-place update on an existing environment: it
# changes metadata only, and never the secret, its versions, or its name.

# express-session secret; injected as env SECRET (the name scripts/server.js reads).
resource "aws_secretsmanager_secret" "session" {
  name                    = local.secret_session_name
  description             = "MMGIS ${var.environment} express-session secret (injected as env SECRET). Value generated by the CI secret bootstrap (#248) on first deploy if empty; never overwritten."
  recovery_window_in_days = var.secret_recovery_window_days
}

resource "aws_secretsmanager_secret" "seed_username" {
  name                    = local.secret_seed_user_name
  description             = "MMGIS ${var.environment} superadmin seed username (SEED_SUPERADMIN_USERNAME). Value generated by the CI secret bootstrap (#248) on first deploy if empty; never overwritten."
  recovery_window_in_days = var.secret_recovery_window_days
}

resource "aws_secretsmanager_secret" "seed_password" {
  name                    = local.secret_seed_pass_name
  description             = "MMGIS ${var.environment} superadmin seed password (SEED_SUPERADMIN_PASSWORD). Value generated by the CI secret bootstrap (#248) on first deploy if empty; never overwritten."
  recovery_window_in_days = var.secret_recovery_window_days
}

# Shared dashboards password; injected only on the publish task (MMGIS_DASHBOARDS_PASSWORD).
resource "aws_secretsmanager_secret" "dashboards_password" {
  name                    = local.secret_dash_pass_name
  description             = "MMGIS ${var.environment} shared dashboards password (MMGIS_DASHBOARDS_PASSWORD). Value generated by the CI secret bootstrap (#248) on first deploy if empty; never overwritten."
  recovery_window_in_days = var.secret_recovery_window_days
}

# External credential: hand-set ONCE per environment, and excluded from CI
# secret generation (CI generates the session/seed/dashboards values; it can
# never invent a Mapbox token). Injected into the admin task only.
resource "aws_secretsmanager_secret" "mapbox_token" {
  name                    = local.secret_mapbox_name
  description             = "MMGIS ${var.environment} Mapbox token (injected as MAPBOX_TOKEN, admin task only). External credential: hand-set once, excluded from CI secret generation."
  recovery_window_in_days = var.secret_recovery_window_days
}
