import { randomUUID } from 'node:crypto'
import { loadMinimalProfile } from './generator.js'

export interface DashboardSpec {
    missionName: string
    layers?: any[]
    view?: { lat: number; lon: number; zoom: number }
    tools?: string[]
    on?: string[]
    time?: Record<string, unknown>
    overrides?: Record<string, { variables: Record<string, unknown> }>
    pageName?: string
}

// Mission-config entry that enables the AgentBridge browser component (Task 7)
export const AGENT_BRIDGE_COMPONENT = {
    name: 'AgentBridge',
    js: 'AgentBridge',
    on: true,
    variables: {},
}

// Injected after generation: `components` is not a template key, and
// /api/configure/add does not run backend validation.
export function ensureAgentBridgeComponent(config: any): void {
    if (!Array.isArray(config.components)) {
        config.components = [AGENT_BRIDGE_COMPONENT]
    }
}

export function buildProfile(spec: DashboardSpec, repoRoot: string): any {
    const minimal = loadMinimalProfile(repoRoot)
    const profile = JSON.parse(JSON.stringify(minimal))
    profile.name = `agent-${spec.missionName}`
    profile.description = 'Generated by the MMGIS MCP server'
    delete profile.output
    profile.tools = Array.from(new Set([...minimal.tools, ...(spec.tools || [])]))
    profile.on = Array.from(new Set([...minimal.on, ...(spec.on || [])]))
    profile.overrides = spec.overrides || {}

    const scaffold = profile.scaffold
    scaffold.msv.mission = spec.missionName
    scaffold.msv.missionFolderName = spec.missionName
    if (spec.view) {
        scaffold.msv.view = [String(spec.view.lat), String(spec.view.lon), String(spec.view.zoom)]
    }
    if (spec.pageName) scaffold.look.pagename = spec.pageName
    if (spec.time) scaffold.time = spec.time
    scaffold.layers = (spec.layers || []).map((l) => ({
        uuid: randomUUID(),
        sublayers: [],
        visibility: true,
        ...l,
    }))
    return profile
}
